### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by juanibiapina** [numa08/git-gitlab#34]
Hi,

We're interested in using this tool at our company. What's the current state of development or your ideas for the future. Are you still maintaining this?

**Comment by numa08** [comment]
Hello,

Thank you using my tool.Yes,  I'm still a maintenance.

But, master branch version (is written by ruby) can not use on Gitlab version 6(and grater)

So, I'm rebuilding by golang now.

**Comment by juanibiapina** [comment]
Thanks for the response.

We've decided to start a new one in bash: https://github.com/juanibiapina/lab

We'll keep an eye on this one in case we want to use it in the future.
